image_slicer/urls.py
from django.urls import path

from . import views

app_name = 'image_slicer'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('<int:image_id>/', views.detail_view, name='detail'),
    path('<int:image_id>/sliced', views.sliced_view, name='sliced')
]

slicedog/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('image_slicer.urls')),
]

image_slicer/models.py
from django.db import models


class Image(models.Model):
    path = models.CharField(max_length=200)
    width = models.IntegerField()
    height = models.IntegerField()

image_slicer/views.py
import os
import urllib.parse
import urllib.request
import uuid

from PIL import Image as PILImage
from django.http import HttpResponse
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from google.cloud import storage

from slicedog.settings import GCP_BUCKET
from .image_slicer import slice_image_iterations
from .models import Image

storage_client = storage.Client()

def index_view(request):

    error_message = ""

    if request.method == 'POST':
        if not request.FILES.get('uploaded-file', False):
            error_message = 'No file selected'
        else:
            uploaded_image = request.FILES['uploaded-file']
            if uploaded_image.size > 5242880:
                error_message = 'Files must be smaller than 5mb'
            else:
                try:
                    image = PILImage.open(uploaded_image)
                    image.verify()
                    uploaded_image.seek(0)

                    filepath = 'image_slicer/' + str(uuid.uuid4())
                    bucket = storage_client.bucket(os.getenv('BUCKET_NAME'))
                    blob = bucket.blob(filepath)
                    blob.upload_from_file(uploaded_image)

                    db_image = Image(
                        path=filepath,
                        width=image.width,
                        height=image.height
                    )
                    db_image.save()
                except Exception as error:
                    print(error)
                    error_message = 'Could not import file as an image'

    images = Image.objects.all()
    return render(request, 'image_slicer/index.html', {
        'images': images,
        'bucket_root': GCP_BUCKET,
        'error_message': error_message
    })


# just serving the dynamically generated image
def sliced_view(request, image_id):
    image_entry = get_object_or_404(Image, pk=image_id)

    image_url = GCP_BUCKET + image_entry.path

    image = PILImage.open(urllib.request.urlopen(image_url))
    response = HttpResponse(content_type="image/jpeg")

    vertical_strips = request.GET.get('v') or 1
    horizontal_strips = request.GET.get('h') or 1
    iterations = request.GET.get('i') or 1

    try:
        image = slice_image_iterations(
            image,
            vstrips=int(vertical_strips),
            hstrips=int(horizontal_strips),
            iterations=int(iterations))
    except ValueError as error:
        return HttpResponseBadRequest(error)

    image = image.convert('RGB')
    image.save(response, 'JPEG')
    return response


def detail_view(request, image_id):
    image_entry = get_object_or_404(Image, pk=image_id)
    return render(request, 'image_slicer/detail.html', {
        'image': image_entry,
        'sliced_url': url_with_querystring(
            reverse('image_slicer:sliced', args=[image_id]),
            request.GET),
        'bucket_root': GCP_BUCKET

    })


def url_with_querystring(path, parameters):
    parameters = {k: v for (k, v) in parameters.items() if v is not None}
    if parameters:
        return path + '?' + urllib.parse.urlencode(parameters)
    return path

image_slicer/templates/image_slicer/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!--JQuery-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

        <link rel="shortcut icon" href="{% static 'image_slicer/favicon-32x32.png' %}"/>

        <title>SliceDog</title>
    </head>
    <body>
    {% block content %}{% endblock content %}
    </body>
</html>

image_slicer/templates/image_slicer/detail.html
{% extends "image_slicer/base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-5">
            <div class="row">
                <div class="col">
                    <h4>Original</h4>
                </div>
                <div class="col text-right">
                    <a href="{% url 'image_slicer:index' %}">choose another</a>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <img src="{{ bucket_root }}{{ image.path }}" class="img-fluid"/>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-lg-2 mt-2">
            <h4>Options</h4>
            <form action="{% url 'image_slicer:detail' image.id %}" method="get">
                <div class="form-row">
                    <div class="form-group col-3 col-lg-12">
                        <label for="vstripsinput">↔️ strips</label>
                        <input type="number" min="1" max="{{ image.height }}"class="form-control" id="vstripsinput"
                               name="v" value="{{request.GET.v}}" required/>
                    </div>
                    <div class="form-group col-3 col-lg-12">
                        <label for="hstripsinput">↕️ strips</label>
                        <input type="number" min="1" max="{{ image.width }}"class="form-control" id="hstripsinput"
                               name="h" value="{{request.GET.h}}" required/>
                    </div>
                    <div class="form-group col-3 col-lg-12">
                        <label for="iterations">Iterations</label>
                        <input type="number" class="form-control" id="iterations"
                               name="i" value="{{request.GET.i}}" min="1" max="50" required/>
                    </div>
                    <div class="form-group col-3 col-lg-12 text-center my-auto">
                        <input type="submit"class="btn btn-primary" value="Slice">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-12 col-lg-5">
            <h4>Sliced</h4>
            <a href="{{ sliced_url }}">
                <img src="{{ sliced_url }}" class="img-fluid"/>
            </a>
        </div>
    </div>
</div>
{% endblock content %}

image_slicer/templates/image_slicer/index.html
{% extends "image_slicer/base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h2>Pick an image to slice</h2>
        </div>
        <div class="col text-right">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label class="btn btn-primary mt-1" for="my-file-selector">
                    <input id="my-file-selector" type="file" name="uploaded-file" style="display:none"
                    onchange="
                    if (this.files[0].name){
                        var filename = this.files[0].name.length>20 ? this.files[0].name.substring(0,20) + '...' : this.files[0].name;
                        $('#upload-button').text('Upload ' + filename);
                        $('#upload-button').css('display','inline');
                    }">
                    Browse
                </label>
                <!--<div class="form-group">-->
                    <!--<input type="file" name="uploaded-file">-->
                <!--</div>-->
                <br>
                <span class='label label-info text-danger'>
                    {{ error_message }}
                </span>
                <button type="submit" class="btn btn-secondary mr-1" id="upload-button" style="display:none">
                    Upload
                </button>
            </form>
        </div>
    </div>

    <div class="row">
            {% for image in images %}
            <div class="col-sm-12 col-md-6 col-lg-4 text-center my-auto">
                <a href="{% url 'image_slicer:detail' image.id %}">
                    <img src="{{ bucket_root }}{{ image.path }}" class="img-fluid m-1" width="100%">
                </a>
            </div>
            {% endfor %}
    </form>
    </div>
    <div class="row">

    </div>
</div>
{% endblock content %}